name: Release

on:
  push:
    tags:
      - main
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install goreleaser
      run: |
        curl -sL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | bash

    - name: Build and release
      run: |
        goreleaser